"""Optional Claude wiring: configure the MCP server, install its deps, verify it starts.

Never fatal — the graph is complete and usable without Claude. Failures show EMB-51 as
a warning and the flow continues.

The server is configured through `mcp/.env`, which `server.py` loads from its OWN
directory. That is deliberate: it is the only configuration that survives a launch from
another directory, a GUI launch that inherits no shell exports, or a health check run
from an ordinary prompt. Nothing here depends on the environment the user happened to
start their client from.
"""

import os
import sys

from installer import errors, stack, ui

# Written into mcp/.env alongside the password. These restate config.py's own defaults,
# spelled out as editable keys so pointing the server elsewhere is a file edit rather
# than an environment puzzle.
MCP_ENV_DEFAULTS = {
    "QDRANT_URL": "http://localhost:6333",
    "ARANGO_URL": "http://localhost:8529",
    "ARANGO_DATABASE": "technology_kg",
    "ARANGO_USER": "root",
    "EMBED_URL": "http://localhost:8100/embed",
}

MCP_ENV_HEADER = (
    "# Generated by embeddington-setup — configuration for the bundled MCP server.\n"
    "# ARANGO_PASSWORD is the root password of your LOCAL ArangoDB container, copied\n"
    "# from consumer/.env. Nothing outside this machine ever sees it.\n"
)


def _fill_empty_password(env_file, password):
    """Give a present-but-empty ARANGO_PASSWORD a value; return whether one was set.

    `cp .env.example .env` leaves `ARANGO_PASSWORD=` in place — a key that a
    merge-if-absent pass skips as "already present", leaving the server unable to start
    for a user who did exactly what the docs told them to.

    Args:
        env_file: Path to an existing mcp/.env.
        password: The value to write.

    Returns:
        True iff an empty password line was replaced.
    """
    lines = env_file.read_text().splitlines(keepends=True)
    for i, line in enumerate(lines):
        if line.startswith("ARANGO_PASSWORD=") and not line.split("=", 1)[1].strip():
            lines[i] = f"ARANGO_PASSWORD={password}\n"
            env_file.write_text("".join(lines))
            return True
    return False


def ensure_mcp_env(repo_root):
    """Write mcp/.env from consumer/.env so the server needs no shell environment.

    Idempotent and non-destructive: an existing file keeps every value the user set;
    only missing keys are added, and only an empty password is filled. Never raises, and
    never logs, prints, or returns the password value.

    Args:
        repo_root: The clone root (consumer/ and mcp/ live beneath it).

    Returns:
        "created" | "filled" | "merged" | "unchanged" | "no-password" (the last when
        consumer/.env holds no usable password — the caller reports, nothing is written).
    """
    try:
        password = stack.read_password(repo_root / "consumer" / ".env")
    except errors.SetupError:
        return "no-password"

    target = repo_root / "mcp" / ".env"
    values = dict(MCP_ENV_DEFAULTS, ARANGO_PASSWORD=password)

    if not target.exists():
        # 0600 from birth (O_CREAT|O_EXCL with the mode), never write-then-chmod: under
        # the default umask that leaves a window where any local user can read it.
        fd = os.open(target, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o600)
        with os.fdopen(fd, "w") as handle:
            handle.write(MCP_ENV_HEADER + "".join(f"{k}={v}\n" for k, v in values.items()))
        return "created"

    # Tighten BEFORE writing a secret into a file that may have been created 0644.
    os.chmod(target, 0o600)
    filled = _fill_empty_password(target, password)
    added = stack.merge_env_keys(target, values)
    if filled:
        return "filled"
    return "merged" if added else "unchanged"


def offer_claude_wiring(console, run, repo_root, *, assume_yes, which=None, input_fn=input):
    """Offer MCP dependency install; return installed|skipped|no-claude|failed.

    Args:
        console: rich Console for output.
        run: Callable that runs a subprocess command (takes cmd argv list).
        repo_root: Path to the repo root (to locate mcp/requirements.txt).
        assume_yes: If True, skip prompts and assume affirmative answers.
        which: Callable to locate a binary on PATH (default: shutil.which).
        input_fn: Callable to read user input (default: builtins.input).

    Returns:
        A status string:
        - "no-claude": Claude Code not found on PATH
        - "skipped": User declined the offer
        - "installed": Dependencies installed successfully
        - "failed": pip install failed (shown as a warning, not raised)
    """
    import shutil

    which = shutil.which if which is None else which
    if which("claude") is None:
        console.print(
            "[dim]Claude Code isn't on your PATH. Install it later and see the README's "
            "'query with Claude' section — the graph works either way.[/dim]"
        )
        return "no-claude"
    if not ui.confirm(
        console,
        "Claude Code detected. Wire up the embeddington MCP server (installs mcp/ deps)?",
        default=True,
        assume_yes=assume_yes,
        input_fn=input_fn,
    ):
        return "skipped"
    req = repo_root / "mcp" / "requirements.txt"
    result = run([sys.executable, "-m", "pip", "install", "-r", str(req)])
    if result.rc != 0:
        ui.show_error(
            console,
            errors.SetupError(
                "EMB-51",
                "Installing the MCP server's dependencies failed (the graph itself is fine).",
                f"Run `pip install -r {req}` manually to see why; then just launch Claude "
                "from the repo root with consumer/.env loaded.",
            ),
        )
        return "failed"
    # [CRITIC] The deps just landed in THIS venv, but .mcp.json launches the server with
    # a bare python3 — the recipe must activate the venv first or the server Claude
    # starts can't import them. (Implementer: verify the interpreter .mcp.json actually
    # names and keep this recipe consistent with it.)
    console.print(
        "\n[green]✓[/green] MCP deps installed. To query the graph:\n"
        "    [bold]cd <your clone>[/bold]\n"
        "    [bold]. .venv/bin/activate && set -a; . consumer/.env; set +a && claude[/bold]\n"
        "  Claude Code auto-discovers the repo's .mcp.json — approve the 'embeddington' "
        "server when prompted. The venv activation matters: the MCP server runs with "
        "whatever python3 is on PATH.\n"
        "  [dim]Claude Desktop instead? cp mcp/.env.example mcp/.env, set ARANGO_PASSWORD, "
        "see mcp/README.md.[/dim]"
    )
    return "installed"
