"""Optional Claude wiring: configure the MCP server, install its deps, verify it starts.

Never fatal — the graph is complete and usable without Claude. Failures show EMB-51 as
a warning and the flow continues.

The server is configured through `mcp/.env`, which `server.py` loads from its OWN
directory. That is deliberate: it is the only configuration that survives a launch from
another directory, a GUI launch that inherits no shell exports, or a health check run
from an ordinary prompt. Nothing here depends on the environment the user happened to
start their client from.
"""

import os
import subprocess
import sys
from dataclasses import dataclass

from installer import errors, stack, ui

# Written into mcp/.env alongside the password. These restate config.py's own defaults,
# spelled out as editable keys so pointing the server elsewhere is a file edit rather
# than an environment puzzle.
MCP_ENV_DEFAULTS = {
    "QDRANT_URL": "http://localhost:6333",
    "ARANGO_URL": "http://localhost:8529",
    "ARANGO_DATABASE": "technology_kg",
    "ARANGO_USER": "root",
    "EMBED_URL": "http://localhost:8100/embed",
}

MCP_ENV_HEADER = (
    "# Generated by embeddington-setup — configuration for the bundled MCP server.\n"
    "# ARANGO_PASSWORD is the root password of your LOCAL ArangoDB container, copied\n"
    "# from consumer/.env. Nothing outside this machine ever sees it.\n"
)


def _fill_empty_password(env_file, password):
    """Give a present-but-empty ARANGO_PASSWORD a value; return whether one was set.

    `cp .env.example .env` leaves `ARANGO_PASSWORD=` in place — a key that a
    merge-if-absent pass skips as "already present", leaving the server unable to start
    for a user who did exactly what the docs told them to.

    Args:
        env_file: Path to an existing mcp/.env.
        password: The value to write.

    Returns:
        True iff an empty password line was replaced.
    """
    lines = env_file.read_text().splitlines(keepends=True)
    for i, line in enumerate(lines):
        if line.startswith("ARANGO_PASSWORD=") and not line.split("=", 1)[1].strip():
            lines[i] = f"ARANGO_PASSWORD={password}\n"
            env_file.write_text("".join(lines))
            return True
    return False


def ensure_mcp_env(repo_root):
    """Write mcp/.env from consumer/.env so the server needs no shell environment.

    Idempotent and non-destructive: an existing file keeps every value the user set;
    only missing keys are added, and only an empty password is filled. Never raises, and
    never logs, prints, or returns the password value.

    Args:
        repo_root: The clone root (consumer/ and mcp/ live beneath it).

    Returns:
        "created" | "filled" | "merged" | "unchanged" | "no-password" (the last when
        consumer/.env holds no usable password — the caller reports, nothing is written).
    """
    try:
        password = stack.read_password(repo_root / "consumer" / ".env")
    except errors.SetupError:
        return "no-password"

    target = repo_root / "mcp" / ".env"
    values = dict(MCP_ENV_DEFAULTS, ARANGO_PASSWORD=password)

    if not target.exists():
        # 0600 from birth (O_CREAT|O_EXCL with the mode), never write-then-chmod: under
        # the default umask that leaves a window where any local user can read it.
        fd = os.open(target, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o600)
        with os.fdopen(fd, "w") as handle:
            handle.write(MCP_ENV_HEADER + "".join(f"{k}={v}\n" for k, v in values.items()))
        return "created"

    # Tighten BEFORE writing a secret into a file that may have been created 0644.
    os.chmod(target, 0o600)
    filled = _fill_empty_password(target, password)
    added = stack.merge_env_keys(target, values)
    if filled:
        return "filled"
    return "merged" if added else "unchanged"


def offer_claude_wiring(console, run, repo_root, *, assume_yes, which=None, input_fn=input):
    """Configure the MCP server, install its deps, prove it starts, and offer reach.

    Order matters. mcp/.env is written FIRST and unconditionally — before the check for
    the Claude Code CLI — because a Claude Desktop user has no CLI on PATH and needs that
    file more than anyone: a GUI app inherits no shell exports at all.

    Never fatal. Every failure here is shown and stepped over; the graph is complete and
    queryable without any of it.

    Args:
        console: rich Console for output.
        run: Callable that runs a subprocess command (takes cmd argv list).
        repo_root: Path to the repo root.
        assume_yes: If True, skip prompts and assume affirmative answers.
        which: Callable to locate a binary on PATH (default: shutil.which).
        input_fn: Callable to read user input (default: builtins.input).

    Returns:
        WiringResult describing each half of the outcome.
    """
    import shutil

    which = shutil.which if which is None else which
    env_status = ensure_mcp_env(repo_root)
    if env_status == "no-password":
        console.print(
            "[yellow]Couldn't read a password from consumer/.env, so mcp/.env wasn't "
            "written — Claude access will need it set by hand.[/yellow]"
        )

    if which("claude") is None:
        console.print(
            "[dim]Claude Code isn't on your PATH. mcp/.env is written and ready, so "
            "Claude Desktop works once you point it at mcp/server.py (see mcp/README.md); "
            "the graph itself works either way.[/dim]"
        )
        return WiringResult(env_status, "no-claude", "not-run", "not-offered")

    if not ui.confirm(
        console,
        "Claude Code detected. Wire up the embeddington MCP server (installs mcp/ deps)?",
        default=True,
        assume_yes=assume_yes,
        input_fn=input_fn,
    ):
        return WiringResult(env_status, "skipped", "not-run", "not-offered")

    req = repo_root / "mcp" / "requirements.txt"
    result = run([sys.executable, "-m", "pip", "install", "-r", str(req)])
    if result.rc != 0:
        ui.show_error(
            console,
            errors.SetupError(
                "EMB-51",
                "Installing the MCP server's dependencies failed (the graph itself is fine).",
                f"Run `.venv/bin/pip install -r {req}` manually to see why.",
            ),
        )
        return WiringResult(env_status, "failed", "not-run", "not-offered")

    verify_status, detail = verify_mcp_server(run, repo_root)
    if verify_status != "verified":
        # Shown, never raised: a server that won't start costs the user nothing they
        # already had, and the data update that preceded this is worth keeping.
        ui.show_error(console, mcp_verification_error(verify_status, detail))
        return WiringResult(env_status, "installed", verify_status, "not-offered")

    console.print("\n[green]✓[/green] MCP server verified — it starts and answers.")
    registration = offer_user_scope(
        console, run, repo_root, assume_yes=assume_yes, input_fn=input_fn
    )

    if registration in ("registered", "refreshed"):
        console.print(
            f"  Registered as [bold]{USER_SCOPE_NAME}[/bold] — run [bold]claude[/bold] "
            "from anywhere and it's there."
        )
    else:
        console.print(
            "  To query the graph: [bold]cd <your clone> && claude[/bold], then approve "
            "the 'embeddington' server. No venv activation, no exported password — "
            "mcp/.env carries the configuration."
        )
    return WiringResult(env_status, "installed", verify_status, registration)


def ensure_claude_wiring(console, run, repo_root):
    """Prompt-free wiring refresh for the update path. Never raises, never asks.

    Mirrors the cron step's split: refresh what the user already has, never introduce
    something that needs consent. That is what makes it safe to run from an unattended
    nightly update — and what lets an install broken by the old configuration repair
    itself without anybody doing anything.

    The server is only probed when its dependencies are actually installed. A user who
    declined Claude wiring should not be nagged about a component they never wanted.

    Args:
        console: rich Console for output.
        run: runner.run-compatible callable.
        repo_root: the clone root.

    Returns:
        WiringResult (deps here reports what was found, not what was installed).
    """
    env_status = ensure_mcp_env(repo_root)
    if not mcp_deps_installed(run, repo_root):
        return WiringResult(env_status, "absent", "not-run", "not-offered")

    verify_status, detail = verify_mcp_server(run, repo_root)
    if verify_status not in ("verified", "stack"):
        # "stack" is the containers being down mid-update, not a wiring problem, and it
        # resolves itself; anything else is worth a word.
        ui.show_error(console, mcp_verification_error(verify_status, detail))

    return WiringResult(env_status, "present", verify_status, refresh_user_scope(run, repo_root))


# Generous: the server's startup sanity check makes real calls to the local stores, and a
# cold container answers slowly. This only bounds a hang, it is not a latency budget.
MCP_VERIFY_TIMEOUT = 60


def _stderr_tail(text, lines=3):
    """The last few non-blank lines — the part that names the actual failure."""
    kept = [line for line in (text or "").splitlines() if line.strip()]
    return "\n".join(kept[-lines:]).strip()


def _diagnose(res):
    """Classify a probe result into (status, detail).

    Every one of these reaches the user's client as the same "Connection closed", so the
    wizard's whole value here is telling them apart. Signatures are taken from the
    server's own startup paths, not guessed.

    Args:
        res: RunResult from the probe spawn.

    Returns:
        (status, detail) where status is verified | no-interpreter | deps | password |
        stack | unknown.
    """
    text = f"{res.err or ''}\n{res.out or ''}"
    if res.rc == 0:
        return "verified", ""
    if res.rc == 127 or "command not found" in text:
        return "no-interpreter", _stderr_tail(text)
    if "No module named" in text:
        return "deps", _stderr_tail(text)
    if "Missing required env var" in text:
        return "password", _stderr_tail(text)
    if "Refusing to start" in text:
        return "stack", _stderr_tail(text)
    return "unknown", _stderr_tail(text)


def verify_mcp_server(run, repo_root, *, timeout=MCP_VERIFY_TIMEOUT):
    """Actually start the server and see what happens. Never raises.

    Spawns exactly what the client will spawn — the clone's venv interpreter, the
    repo-relative script, the same working directory — with stdin closed. Measured: a
    healthy server takes the EOF, shuts down cleanly, and exits 0.

    Args:
        run: runner.run-compatible callable.
        repo_root: the clone root.
        timeout: seconds before the probe is treated as hung.

    Returns:
        (status, detail) — see _diagnose. "timeout" when the server never exited.
    """
    interpreter = repo_root / ".venv" / "bin" / "python"
    try:
        res = run(
            [str(interpreter), "mcp/server.py"],
            cwd=repo_root,
            timeout=timeout,
            stdin_devnull=True,
        )
    except subprocess.TimeoutExpired:
        return "timeout", f"still running after {timeout}s with stdin closed"
    return _diagnose(res)


_VERIFY_FIXES = {
    "no-interpreter": (
        "The clone's .venv is missing or incomplete. Re-run the install one-liner; it "
        "rebuilds the environment."
    ),
    "deps": (
        "Re-run embeddington-setup and accept the Claude step, or install them yourself "
        "with the clone's own interpreter: .venv/bin/pip install -r mcp/requirements.txt"
    ),
    "password": (
        "Re-run embeddington-setup — it writes mcp/.env from consumer/.env. To do it by "
        "hand, set ARANGO_PASSWORD in mcp/.env to the ARANGO_ROOT_PASSWORD in consumer/.env."
    ),
    "stack": (
        "This is the local stack being down, not the Claude wiring — that part is fine. "
        "Run embeddington-setup --check to see which container isn't answering."
    ),
    "timeout": (
        "The server started but never exited when its input closed. Run it by hand to "
        "watch it: .venv/bin/python mcp/server.py < /dev/null"
    ),
    "unknown": (
        "Run the probe yourself to see the whole error: .venv/bin/python mcp/server.py < /dev/null"
    ),
}


def mcp_verification_error(status, detail):
    """Turn a non-verified probe status into a SetupError; None when it verified.

    Args:
        status: a status from verify_mcp_server.
        detail: the accompanying detail (the server's own words, when it had any).

    Returns:
        errors.SetupError (EMB-52), or None when status is "verified".
    """
    if status == "verified":
        return None
    said = f" It said: {detail}" if detail else ""
    return errors.SetupError(
        "EMB-52",
        f"The MCP server didn't start when I probed it ({status}).{said}",
        _VERIFY_FIXES.get(status, _VERIFY_FIXES["unknown"]),
    )


# Distinct from the project-scoped server in .mcp.json on purpose. Measured: the same
# name in two scopes makes the client print a standing "defined in multiple scopes with
# different endpoints" warning on every listing, and the project entry wins in-project
# anyway. Two names, no warning, and the scopes stay tellable apart.
USER_SCOPE_NAME = "embeddington-local"


def _mcp_add_argv(repo_root):
    """The registration command. Absolute paths are mandatory, not tidy: measured, a
    relative command under user scope is never spawned at all from another directory."""
    return [
        "claude",
        "mcp",
        "add",
        USER_SCOPE_NAME,
        "--scope",
        "user",
        "--",
        str(repo_root / ".venv" / "bin" / "python"),
        str(repo_root / "mcp" / "server.py"),
    ]


def user_scope_present(run):
    """True iff a user-scope registration under our name exists. Never raises."""
    return run(["claude", "mcp", "get", USER_SCOPE_NAME]).rc == 0


def register_user_scope(run, repo_root):
    """Point the user-scope registration at THIS clone; return whether it stuck.

    Remove-then-add, because `claude mcp add` refuses an existing name — and does so
    while exiting 0, so its return code proves nothing. Success is confirmed by reading
    the registration back, which is the only trustworthy signal available.

    Args:
        run: runner.run-compatible callable.
        repo_root: the clone root the registration should point at.

    Returns:
        True iff a registration exists afterwards.
    """
    run(["claude", "mcp", "remove", USER_SCOPE_NAME, "-s", "user"])  # absent is fine
    run(_mcp_add_argv(repo_root))
    return user_scope_present(run)


def remove_user_scope(run):
    """Drop the user-scope registration (uninstall). Never raises."""
    run(["claude", "mcp", "remove", USER_SCOPE_NAME, "-s", "user"])
    return not user_scope_present(run)


def offer_user_scope(console, run, repo_root, *, assume_yes, input_fn=input):
    """Offer to make the server reachable from every directory.

    An existing registration is refreshed silently rather than re-offered — the same
    never-re-nag contract the cron step follows. Unattended runs cannot consent, so they
    neither prompt nor register.

    Returns:
        "registered" | "refreshed" | "declined" | "skipped-unattended" | "failed".
    """
    if assume_yes:
        return "skipped-unattended"
    if user_scope_present(run):
        return "refreshed" if register_user_scope(run, repo_root) else "failed"
    if not ui.confirm(
        console,
        "Make the graph queryable from every directory, not just this clone?",
        default=True,
        input_fn=input_fn,
    ):
        return "declined"
    return "registered" if register_user_scope(run, repo_root) else "failed"


def refresh_user_scope(run, repo_root):
    """Update path: repoint an existing registration; never create one.

    Adding a registration is a consent-bearing act, and an unattended nightly update is
    the wrong place to perform one.

    Returns:
        "refreshed" | "absent" | "failed".
    """
    if not user_scope_present(run):
        return "absent"
    return "refreshed" if register_user_scope(run, repo_root) else "failed"


def mcp_deps_installed(run, repo_root):
    """True iff the server's dependencies import under the interpreter that runs it.

    Deliberately not `find_spec` from the wizard: that tests the WRONG interpreter, and
    the repo's own `mcp/` directory is importable as a namespace package, so it can
    report success with no SDK installed at all.
    """
    interpreter = repo_root / ".venv" / "bin" / "python"
    return run([str(interpreter), "-c", "import fastmcp"]).rc == 0


@dataclass(frozen=True)
class WiringResult:
    """What the Claude step actually accomplished, for the receipt to report honestly."""

    env: str  # created | filled | merged | unchanged | no-password
    deps: str  # installed | skipped | failed | no-claude
    verify: str  # verified | deps | password | stack | ... | not-run
    # registered | refreshed | declined | skipped-unattended | failed | not-offered
    registration: str
