"""Bring up the local stack: generate .env, compose up --build, wait for readiness.

Password hygiene rules (Global Constraints): generated with secrets.token_urlsafe(24),
file mode 0o600, an existing .env is never overwritten, and the value is never printed
or logged anywhere in this module.
"""

import os
import secrets
import time

from installer.errors import SetupError

ENV_HEADER = (
    "# Generated by embeddington-setup. This is the root password for your LOCAL\n"
    "# ArangoDB container only; nothing outside this machine ever sees it.\n"
)


def ensure_env_file(consumer_dir, *, token_fn=None):
    """Create consumer/.env with a generated password iff it doesn't already exist.

    [CRITIC] The file must be 0o600 from birth (O_CREAT|O_EXCL with the mode), never
    write_text-then-chmod: under the default umask that leaves a window where any local
    user can read the root password. O_EXCL also makes a concurrent-create a loud
    failure instead of a silent overwrite.
    """
    token_fn = secrets.token_urlsafe if token_fn is None else token_fn
    env_file = consumer_dir / ".env"
    if env_file.exists():
        return env_file
    fd = os.open(env_file, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o600)
    with os.fdopen(fd, "w") as handle:
        handle.write(ENV_HEADER + f"ARANGO_ROOT_PASSWORD={token_fn(24)}\n")
    return env_file


def read_password(env_file):
    """Read ARANGO_ROOT_PASSWORD out of a consumer/.env; EMB-33 if unusable."""
    try:
        lines = env_file.read_text().splitlines()
    except OSError:
        lines = []
    for line in lines:
        if line.startswith("ARANGO_ROOT_PASSWORD="):
            value = line.split("=", 1)[1].strip()
            if value and value != "change-me":
                return value
    raise SetupError(
        "EMB-33",
        f"{env_file} exists but doesn't contain a usable ARANGO_ROOT_PASSWORD.",
        "Open it and set ARANGO_ROOT_PASSWORD to any non-empty value (not 'change-me'), "
        "or delete the file and re-run so I can generate one.",
    )


def compose_up(run, consumer_dir):
    """docker compose up -d --build, streamed live (the embed build takes 10-20 min)."""
    result = run(["docker", "compose", "up", "-d", "--build"], cwd=consumer_dir, stream=True)
    if result.rc != 0:
        raise SetupError(
            "EMB-31",
            "docker compose up failed — the error is in the output just above.",
            "Fix what compose complained about (ports, disk, daemon), then re-run the "
            "installer; it picks up where it left off.",
        )


def _up(http_get, url, accept):
    try:
        status, _ = http_get(url)
        return status in accept
    except OSError:
        return False


def wait_for_services(
    console, http_get, *, sleep=None, clock=None, store_timeout=180, embed_timeout=1800
):
    """Poll until qdrant+arango (store_timeout) and embed (embed_timeout) answer.

    Separate deadlines because the stores are prebuilt pulls (up in seconds) while the
    embed service downloads ~2 GB of model weights on first start. [CRITIC] The wait
    shows a live elapsed-time status: a silent poll of up to 30 minutes reads as a hang
    and trains users to Ctrl-C a healthy install.
    """
    sleep = time.sleep if sleep is None else sleep
    clock = time.monotonic if clock is None else clock

    with console.status("[cyan]Waiting for the stores...[/cyan]") as status:
        start = clock()
        while not (
            _up(http_get, "http://localhost:6333/collections", {200})
            and _up(http_get, "http://localhost:8529/_api/version", {200, 401})
        ):
            if clock() - start > store_timeout:
                raise SetupError(
                    "EMB-31",
                    "Qdrant/ArangoDB containers didn't come up in time.",
                    "Check `docker compose ps` and `docker compose logs` in consumer/, "
                    "then re-run.",
                )
            status.update(f"[cyan]Waiting for the stores... {int(clock() - start)}s[/cyan]")
            sleep(5)

        start = clock()
        while not _up(http_get, "http://localhost:8100/", {200, 404, 405}):
            if clock() - start > embed_timeout:
                raise SetupError(
                    "EMB-32",
                    "The embed service didn't come up — its first build downloads ~2 GB of "
                    "model weights, and that appears to have stalled or failed.",
                    "Run `docker compose logs embed` in consumer/ to see why; a plain retry "
                    "(`docker compose up -d --build`) resumes a dropped download cleanly.",
                )
            status.update(
                f"[cyan]Embed service warming up (first run pulls ~2 GB of model weights "
                f"— the Dude abides)... {int(clock() - start) // 60}m[/cyan]"
            )
            sleep(5)
